# Dovecot Community Edition configuration for Eazzio Mail
protocols = imap lmtp pop3
listen = *

mail_location = maildir:/var/mail/vhosts/%d/%n
mail_uid = vmail
mail_gid = vmail
mail_privileged_group = vmail

# LMTP Service configuration for delivery handoff
service lmtp {
  inet_listener lmtp {
    address = 0.0.0.0
    port = 24
  }
}

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

ssl = yes
ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key

auth_mechanisms = plain login
passdb {
  driver = static
  args = nopassword=y
}
userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
}
