-- Down Migration: 002_rls_and_security_policies.down.sql
DROP POLICY IF EXISTS audit_log_select_policy ON audit_log;
DROP POLICY IF EXISTS audit_log_insert_only ON audit_log;
DROP POLICY IF EXISTS messages_mailbox_policy ON messages;
DROP POLICY IF EXISTS mailbox_owner_policy ON mailboxes;

ALTER TABLE mailboxes DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE labels DISABLE ROW LEVEL SECURITY;
ALTER TABLE threads DISABLE ROW LEVEL SECURITY;
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE filters DISABLE ROW LEVEL SECURITY;
ALTER TABLE domains DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
