DROP POLICY IF EXISTS label_isolation_policy ON labels;
DROP POLICY IF EXISTS folder_isolation_policy ON folders;
DROP POLICY IF EXISTS message_isolation_policy ON messages;
DROP POLICY IF EXISTS mailbox_isolation_policy ON mailboxes;

ALTER TABLE domain_aliases DISABLE ROW LEVEL SECURITY;
ALTER TABLE filters DISABLE ROW LEVEL SECURITY;
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE threads DISABLE ROW LEVEL SECURITY;
ALTER TABLE labels DISABLE ROW LEVEL SECURITY;
ALTER TABLE folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE mailboxes DISABLE ROW LEVEL SECURITY;
